name: "Zap testing"

on:
  push:
    branches:
      - feature/xmlreport
     
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          token: ${{ secrets.GIT_TOKEN }}
          target: 'https://log8100-10-dev-2addd04e4cb7.herokuapp.com'
          cmd_options: '-x report_xml.xml -a'

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v3
        with:
          name: zap-reports-test
          path: |
            report_json.json
            report_md.md
            report_html.html
            report_xml.xml          
