name: "Zap testing"

on:
  push:
    branches:
      - feature/xmlreport

jobs:            
  zap_scan_dev:
    runs-on: ubuntu-latest
    name: Dev - Zap scanning
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          token: ${{ secrets.GIT_TOKEN }}
          target: 'https://log8100-10-dev-2addd04e4cb7.herokuapp.com'
          cmd_options: '-x report_xml.xml -a'

